### ISSUE TITLE
Cannot Load data in a column within datagrid

### ISSUE THREAD

**Issue by mtsang** [formio/ng2-formio#113] opened 2017-05-26 22:21 UTC
I have confirmed it works fine without fields embedded in a datagrid, but when it's embedded in a column in a datagrid, data does not load.

Reproducible example here:

<formio src='https://auicqnmuwlxvnoh.form.io/form4' [submission]='{"data":{"datagrid":[{"name":"submissionname","yodel":"submissionyodel"},{"name":"submissionname2","yodel":"submissionyodel2"}],"showdatagrid":true}}'></formio>

**Comment by mtsang** [comment] 2017-05-26 22:31
same appears to apply if it's embedded within a table within a datagrid

**Comment by mtsang** [comment] 2017-05-26 23:02
actually this is a low priority since datagrid gives column functionality already

**Comment by travist** [comment] 2017-05-27 02:36
I found the cause. The fix for this will be in the next build.

**Comment by travist** [comment] 2017-05-27 03:46
RC19 fixes this. Thanks for testing.

**Closed by travist** 2017-05-27 03:46 UTC

**Comment by iamsandeepgupta** [comment] 2018-11-21 09:42
@mikethm are u able to bind data to datagrid with gridtype = 'form'.
if yes, please tell me how u have done.... i have been struggling with this issue since 1 week.
