### ISSUE TITLE
Date value does not pass 

### ISSUE THREAD

**Issue by srinathswaminathan** [formio/ng2-formio#47] opened 2017-01-23 06:36 UTC
when i save the data in database the date value does not pass,
it show date is null and date is not trigger into the onChange event also, 
here dateofbirth is date.
1.	city:"chennai"
2.	companyname:"ssr"
3.	country:"india"
4.	currency:""
5.	dateofbirth:null
6.	description:"comment"
7.	email1:"admin@gmail.com"
8.	filtername:""

**Comment by travist** [comment] 2017-01-23 17:09
I just pushed up a change over the weekend that changes the behavior of the datetime component. Have you tested with the latest version?

**Comment by srinathswaminathan** [comment] 2017-01-24 05:06
oh now i am using ng2formio latest, you may tell me about what can i change to myself.

**Comment by srinathswaminathan** [comment] 2017-01-25 05:34
now i am using your latest committed datetime code but the date value does not pass,how to fix it.

**Comment by srinathswaminathan** [comment] 2017-01-27 13:27
Hi,
now i take latest version but it shows this kind of error.
node_modules/ng2-formio-master/src/components/datetime/datetime.ts
(54,9): error
TS2349: Cannot invoke an expression whose type lacks a call signature.

**Comment by harryhahn** [comment] 2017-01-27 21:46
I have the same issue 
Version 0.7.0

**Comment by travist** [comment] 2017-01-28 16:01
I will take a look at this over the weekend and see if I can determine the cause. Thanks.

**Comment by srinathswaminathan** [comment] 2017-01-31 10:11
Hi travist any update?

**Comment by srinathswaminathan** [comment] 2017-02-01 12:40
this error shows the datetime.ts file: 

line no:54
this.component.control.setValue(date)

**Comment by travist** [comment] 2017-02-01 13:58
Hello everyone. I am aware of issues with the datetime and am looking into fixing it soon. The reason it is taking me longer than usual is I am in the process of replacing the datetime implementation with using flatpickr instead.  https://github.com/chmln/flatpickr

**Comment by sivakamihs** [comment] 2017-03-02 11:56
Hi travist,

May I know any updates in ng2formio datetime to pass value

**Comment by travist** [comment] 2017-03-06 02:27
This is now resolved with beta.1 release!  We are now using the flatpickr module which is much easier to deal with.

**Closed by travist** 2017-03-06 02:27 UTC
